### ISSUE TITLE
Create Alert for Photo of Receipt

### ISSUE THREAD

**Issue by jonahz5222** [jonahz5222/grocer#13]
Alert should be presented when pressing the "add" button on the Purchases view, and should be an alert of type .ActionSheet, with 3 options, "Take a Photo", "Use a Photo from Library", and "Cancel"

**Comment by jonahz5222** [comment]
Also this is dependent on #10

**Comment by qgvc4** [comment]
Is this done by #12 ? @jonahz5222 @Jordendarc
